version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hibernate
      PGDATA: /data/postgres
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"